

try {
    let a = 2;
    //throw new Error('a');
} catch (er) {
    //console.log(a);
}
console.log(a);
